# Generated by Django 4.2.16 on 2026-05-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField()),
                ('source_type', models.CharField(choices=[('api', 'API'), ('scrape', 'Web Scrape')], default='scrape', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('error', 'Error'), ('paused', 'Paused')], default='pending', max_length=10)),
                ('frequency', models.CharField(choices=[('1h', 'Every 1 Hour'), ('6h', 'Every 6 Hours'), ('12h', 'Every 12 Hours'), ('24h', 'Every 24 Hours')], default='6h', max_length=5)),
                ('selector_config', models.JSONField(blank=True, default=dict)),
                ('is_builtin', models.BooleanField(default=False)),
                ('last_scraped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sources',
                'ordering': ['-created_at'],
            },
        ),
    ]
