# Generated by Django 4.2.16 on 2026-05-01 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_response', models.TextField()),
                ('skills', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'learning_paths',
            },
        ),
    ]
