# Generated by Django 4.2.16 on 2026-05-01 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('design', 'Design'), ('soft', 'Soft')], default='technical', max_length=20)),
                ('weekly_mentions', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'skills',
                'ordering': ['-weekly_mentions'],
            },
        ),
        migrations.CreateModel(
            name='SkillTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('mention_count', models.PositiveIntegerField(default=0)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trends', to='skills.skill')),
            ],
            options={
                'db_table': 'skill_trends',
                'ordering': ['week_start'],
                'unique_together': {('skill', 'week_start')},
            },
        ),
    ]
